language: python
env:
  global:
    - "BLENDER_USER_SCRIPTS=."
    - "PYTHONPATH=."
matrix:
  include:
    - python: "3.5"
      env: "BLENDER_TAR=http://download.blender.org/release/Blender2.79/blender-2.79-linux-glibc219-x86_64.tar.bz2"
    - python: "3.4"
      env: "BLENDER_TAR=http://download.blender.org/release/Blender2.72/blender-2.72-linux-glibc211-x86_64.tar.bz2"
before_install:
  - wget -O - ${BLENDER_TAR} | tar -jxf -
  - mv blender-* blender
install:
  - pip install pytest
  - pip install Pillow
script:
  # This is workaround for older versions of blender (<=2.72)
  # In newer versions it's best to use:
  #
  # --python-exit-code 1
  # --python-expr
  # "import sys;
  # sys.path.extend($(python -c "import sys; print(repr(sys.path))"));
  # import pytest;
  # pytest.main([])"
  - >
    blender/blender
    --factory-startup
    -noaudio
    --background
    --python run_tests.py
    --
    "$(python -c "import sys; print(repr(sys.path))")"
    &&
    exit $(cat result.txt)
